name: Test Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 pytest
    - name: Install pypylon generic
      if: matrix.os == 'windows-latest'
      run: |
        pip install pypylon
    - name: Install requirements
      working-directory: stereo3d
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      working-directory: stereo3d
      run: |
        pytest
